const projectData = [
  {
    category: "web",
    title: "프로젝트: 카제로스 웹 리디자인",
    short_description: "순수 JavaScript와 CSS 애니메이션으로 구현한 시네마틱 프로모션 웹사이트. 사용자의 스크롤(휠)과 상호작용하며 장면이 전환되고, 동적인 텍스트와 이미지 애니메이션을 통해 게임 업데이트의 서사를 영화 예고편처럼 몰입감 있게 전달합니다.",
    image_alt: "카제로스 웹 리디자인 프로젝트 이미지",
    image_src: "images/LostArk.webp",
    modal_image_src: "images/LostArk.webp",
    modal_description: "최후의 날'은 게임의 대규모 업데이트 '카제로스 레이드'를 소개하는 시네마틱 프로모션 웹사이트입니다. 사용자에게 마치 한 편의 영화 예고편을 보는 듯한 몰입감 높은 경험을 제공하여, 업데이트에 대한 기대감을 극대화하는 것을 목표로 제작되었습니다.",
    modal_process: "기획부터 UI/UX 디자인, 개발까지 프로젝트 전반을 주도했습니다. 순수 JavaScript와 CSS만으로 마우스 휠 이벤트에 반응하는 장면 전환 로직과 순차적 애니메이션을 직접 구현하여, '시네마틱 웹'이라는 핵심 콘셉트를 완성했습니다..",
    tags: ["HTML5", "CSS3", "JavaScript", "Vanilla JS", "CSS Animations", "Interactive Web", "UI/UX"],
    display_tags: ["JavaScript", "Interactive Web", "UI/UX"],
    timeline: "2025.10 - 2025.11 (3개월)",
    link: "https://jang-da.github.io/-/"
  },
  {
    category: "ux/ui",
    title: "프로젝트: 밀리의 서재",
    short_description: "Vue.js 기반의 반응형 이커머스 플랫폼을 구축하여 사용자 경험과 성능을 동시에 개선한 프로젝트입니다.",
    image_alt: "밀리의 서재 프로젝트 이미지",
    image_src: "images/millie.jpg",
    modal_image_src: "images/millie.jpg",
    modal_description: "Vue.js와 Tailwind CSS를 사용하여 빠르고 반응성이 뛰어난 이커머스 플랫폼을 구축했습니다. 상품 목록, 장바구니, 결제 시스템 등 핵심 기능을 구현했습니다.",
    modal_process: "프론트엔드 개발 전반을 담당했습니다. 컴포넌트 기반 아키텍처를 설계하여 코드의 재사용성과 유지보수성을 높였습니다. Lighthouse 점수를 90점 이상으로 유지하며 성능 최적화에 집중했습니다.",
    tags: ["Figma", "Mobile" ],
    display_tags: ["Figma", "Mobile"],
    timeline: "2024.07 - 2024.09 (3개월)",
    link: "https://www.figma.com/design/ido2pC98ApIUPXdSwde3sE/%EB%B0%80%EB%A6%AC%EC%9D%98%EC%84%9C%EC%9E%AC-%EB%A6%AC%EB%94%94%EC%9E%90%EC%9D%B8?node-id=0-1&p=f&t=NvSIwKKeILcRqm2h-0"
  },
  {
    category: "Product Page",
    title: "프로젝트: 어린이 비타민 상세페이지",
    short_description: "장노출 사진을 통해 도시의 동적인 아름다움을 포착하고, 빛을 이용해 감성적인 분위기를 연출했습니다.",
    image_alt: "프로젝트 4 이미지",
    image_src: "images/vitamin.jpg",
    modal_image_src: "images/vitamin.jpg",
    modal_description: "도시의 야경과 건축물이 만들어내는 빛의 패턴을 주제로 한 사진 시리즈입니다. 장노출 기법을 활용하여 빛의 궤적을 담아냈습니다.",
    modal_process: "기획, 촬영, 후보정 전 과정을 직접 진행했습니다. Adobe Lightroom과 Photoshop을 사용하여 각 사진의 색감과 구성을 섬세하게 조정하여 주제를 효과적으로 표현했습니다.",
    tags: ["Photography", "Adobe Lightroom"],
    display_tags: ["Photography", "Photoshop",],
    timeline: "2024.05 - 2024.06 (2개월)",
    link: "images/your-project-image.png"
  },
  {
    category: "photo",
    title: "카메라를 통한 세상",
    short_description: "카메라 렌즈는 단순히 피사체를 기록하는 장치가 아니라, 그 자체가 아름다운 자연을 쏟아내는 샘물처럼 묘사됩니다. 렌즈를 통해 본 이상적인 풍경(일몰)이 렌즈 밖의 현실(계곡)로 흘러나오며, 기술과 자연이 하나로 통합되는 상상력을 시각화했습니다",
    image_alt: "도시 야경 사진 프로젝트",
    modal_image_src: "images/photo..png",
    image_src: "images/photo..png",
    modal_description: "도시의 야경과 건축물이 만들어내는 빛의 패턴을 주제로 한 사진 시리즈입니다. 장노출 기법을 활용하여 빛의 궤적을 담아냈습니다.",
    modal_process: "기획, 촬영, 후보정 전 과정을 직접 진행했습니다. Adobe Lightroom과 Photoshop을 사용하여 각 사진의 색감과 구성을 섬세하게 조정하여 주제를 효과적으로 표현했습니다.",
    tags: ["Photography", "Adobe Lightroom", "Art Direction"],
    display_tags: ["Photography", "Lightroom"],
    timeline: "2024.03 - 2024.04 (2개월)",
    link: "#"
  },
  {
    category: "photo",
    title: "장미 한 송이",
    short_description: "초록의 잎사귀 사이, 가장 강렬한 순간을 머금은 붉은 장미 한 송이",
    image_alt: "images/photo2.JPG",
    modal_image_src: "images/photo2.JPG",
    image_src: "images/photo2.JPG",
    modal_description: "도시의 야경과 건축물이 만들어내는 빛의 패턴을 주제로 한 사진 시리즈입니다. 장노출 기법을 활용하여 빛의 궤적을 담아냈습니다.",
    modal_process: "기획, 촬영, 후보정 전 과정을 직접 진행했습니다. Adobe Lightroom과 Photoshop을 사용하여 각 사진의 색감과 구성을 섬세하게 조정하여 주제를 효과적으로 표현했습니다.",
    tags: ["Photography", "Adobe Lightroom", "Art Direction"],
    display_tags: ["Photography", "Lightroom"],
    timeline: "2024.03 - 2024.04 (2개월)",
    link: "#"
  },
  {
    category: "photo",
    title: "소품 촬영",
    short_description: "어느 조용한 오후, 따뜻한 커피 한 잔과 함께 사적인 기록을 펼쳐놓은 순간",
    image_alt: "images/photo3.png",
    modal_image_src: "images/photo3.png",
    image_src: "images/photo3.png",
    modal_description: "도시의 야경과 건축물이 만들어내는 빛의 패턴을 주제로 한 사진 시리즈입니다. 장노출 기법을 활용하여 빛의 궤적을 담아냈습니다.",
    modal_process: "기획, 촬영, 후보정 전 과정을 직접 진행했습니다. Adobe Lightroom과 Photoshop을 사용하여 각 사진의 색감과 구성을 섬세하게 조정하여 주제를 효과적으로 표현했습니다.",
    tags: ["Photography", "Adobe Lightroom", "Art Direction"],
    display_tags: ["Photography", "Lightroom"],
    timeline: "2024.03 - 2024.04 (2개월)",
    link: "#"
  },
]; 